### PR TITLE
Make able to alter add constraint after create table

### LINKED ISSUE #327: Cannot ALTER TABLE to add foreign key newly
## --export output
empty

## Input SQL
```sql
-- dry run --
CREATE TABLE posts (
  content text,
  user_id bigint
);
ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;
```

## Current output
```sql
-- dry run --
CREATE TABLE posts (
  content text,
  user_id bigint
);
```

## Expected output
```sql
-- dry run --
CREATE TABLE posts (
  content text,
  user_id bigint
);
ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;
```

I investigated for couple hours and I figured out that seems like [generateDDLsForAddForeignKey](https://github.com/k0kubun/sqldef/blob/master/schema/generator.go#L674) does not generate ddl nor append to ddls.
following test fails even though it should pass.

```golang
func TestPsqldefAddForeignKeyA(t *testing.T) {
	resetTestDatabase()

	createUsers := "CREATE TABLE users (id BIGINT PRIMARY KEY);\n"
	createPosts := stripHeredoc(`
		CREATE TABLE posts (
		  content text,
		  user_id bigint
		);
		`,
	)
	addForeignKey := "ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;\n"
	assertApplyOutput(t, createUsers+createPosts+addForeignKey, applyPrefix+createUsers+createPosts+addForeignKey)
}
```

### PR DESCRIPTION
**Pull request by tomocrafter**
fixes #327 

I implemented this following another statements like `add policy`.
If it is incorrect and there is better option to implement it, please let me know.

Thank you.

### CODE REVIEW

File: cmd/psqldef/psqldef_test.go [hunk 1]
```diff
@@ -290,6 +290,41 @@ func TestPsqldefAddForeignKey(t *testing.T) {
 	assertApplyOutput(t, createUsers+createPosts+addForeignKey, nothingModified)
 }
 
+func TestPsqldefAddForeignKeyWithAlter(t *testing.T) {
```
Comment (k0kubun) [inline cmd/psqldef/psqldef_test.go:293]: I'm trying to move any new SQL-level tests to `cmd/psqldef/tests.yml` because that's faster and less redundant. Could you move the tests to that place?

**Comment by k0kubun** [comment]
:heart: Thank you for the patch. Please have a look at https://github.com/k0kubun/sqldef/pull/331#discussion_r1045173290. Other places look good!

**Comment by tomocrafter** [comment]
I created this feature following `CREATE POLICY` statement simulation. since it has this issue https://github.com/k0kubun/sqldef/issues/332#issue-1490552012 so this feature also has.
I'm trying to manege to solve it

**Comment by tomocrafter** [comment]
Thank you for reviewing!
I moved all added tests to tests.yml.

**Review by k0kubun — APPROVED** [review]
Thanks!

File: cmd/psqldef/tests.yml [hunk 2]
```diff
@@ -479,3 +479,37 @@ AddArrayColumn:
...
+      content text,
+      user_id bigint
+    );
+  desired: |
+    CREATE TABLE users (id BIGINT PRIMARY KEY);
+    CREATE TABLE posts (
+      content text,
+      user_id bigint
+    );
+    ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;
```
Comment (fumieval) [inline cmd/psqldef/tests.yml:495]: Is it intentional that the parser accepts `ALTER TABLE ONLY` but not `ALTER TABLE`? I expected `mysqldef` to accept the following schema:

```
CREATE TABLE `error_logs`(
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `credential_id` BIGINT NOT NULL,
  `message` TEXT CHARACTER SET utf8mb4 NOT NULL,
  `created_at` DATETIME NOT NULL,
  `resolved` TINYINT(1) NOT NULL);
ALTER TABLE `error_logs`
  ADD CONSTRAINT `fkey`
  FOREIGN KEY(`credential_id`)
  REFERENCES `credentials`(`id`)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;
```

However it produced the following error.

```
found syntax error when parsing DDL "ALTER TABLE `error_logs`
  ADD CONSTRAINT `fkey`
  FOREIGN KEY(`credential_id`)
  REFERENCES `credentials`(`id`)
  ON DELETE CASCADE
  ON UPDATE RESTRICT": syntax error at position 59 near 'foreign'
```
